/*
 * Anzeige.java
 *
 * Created on 26. April 2005, 13:38
 */

package gui;

/**
 *
 * @author  Standard
 */
public class frmAufenthalt extends javax.swing.JFrame {
    public static int WIDTH=450;
    public static int HEIGHT=350;
    public static String TITLE="frmAnzeige: Treffen Sie Ihre Wahl!";
    
    /** Creates new form Anzeige */
    public frmAufenthalt() {
        super(TITLE);
        initComponents();
        setSize(WIDTH, HEIGHT);
        show();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        cmdNotiz = new javax.swing.JButton();
        cmdReservierung = new javax.swing.JButton();
        cmdKunde = new javax.swing.JButton();
        cmdSonstiges = new javax.swing.JButton();
        cmdLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        cmdNotiz.setIcon(new javax.swing.ImageIcon("D:\\Universität\\Informatik2\\Sem6\\Software Engineering 2\\Projekt\\Code\\HICS_v1_0\\gifs\\info.png"));
        cmdNotiz.setText("Notiz");
        cmdNotiz.setMaximumSize(new java.awt.Dimension(95, 25));
        cmdNotiz.setMinimumSize(new java.awt.Dimension(95, 25));
        cmdNotiz.setPreferredSize(new java.awt.Dimension(125, 30));
        cmdNotiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNotizActionPerformed(evt);
            }
        });

        jPanel1.add(cmdNotiz);

        cmdReservierung.setText("Reservierung");
        cmdReservierung.setMaximumSize(new java.awt.Dimension(110, 25));
        cmdReservierung.setMinimumSize(new java.awt.Dimension(110, 25));
        cmdReservierung.setPreferredSize(new java.awt.Dimension(125, 30));
        jPanel1.add(cmdReservierung);

        cmdKunde.setText("Kundendaten");
        cmdKunde.setMaximumSize(new java.awt.Dimension(110, 25));
        cmdKunde.setMinimumSize(new java.awt.Dimension(110, 25));
        cmdKunde.setPreferredSize(new java.awt.Dimension(125, 30));
        cmdKunde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKundeActionPerformed(evt);
            }
        });

        jPanel1.add(cmdKunde);

        cmdSonstiges.setText("Sonstiges");
        cmdSonstiges.setMaximumSize(new java.awt.Dimension(95, 25));
        cmdSonstiges.setMinimumSize(new java.awt.Dimension(95, 25));
        cmdSonstiges.setPreferredSize(new java.awt.Dimension(125, 30));
        jPanel1.add(cmdSonstiges);

        cmdLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/logout.gif")));
        cmdLogout.setText("Ausloggen");
        cmdLogout.setMaximumSize(new java.awt.Dimension(95, 25));
        cmdLogout.setMinimumSize(new java.awt.Dimension(95, 25));
        cmdLogout.setPreferredSize(new java.awt.Dimension(125, 30));
        cmdLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLogoutActionPerformed(evt);
            }
        });

        jPanel1.add(cmdLogout);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void cmdLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLogoutActionPerformed
        // TODO add your handling code here:
        this.hide();
        new frmStart().setVisible(true);
    }//GEN-LAST:event_cmdLogoutActionPerformed

    private void cmdKundeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKundeActionPerformed
        // TODO add your handling code here:
        this.hide();
        new frmAufenthalt().setVisible(true);
    }//GEN-LAST:event_cmdKundeActionPerformed

    private void cmdNotizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNotizActionPerformed
        // TODO add your handling code here:
        this.hide();
        new frmInfo().setVisible(true);
    }//GEN-LAST:event_cmdNotizActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAnzeige().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdKunde;
    private javax.swing.JButton cmdLogout;
    private javax.swing.JButton cmdNotiz;
    private javax.swing.JButton cmdReservierung;
    private javax.swing.JButton cmdSonstiges;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
