/*
 * Anzeige.java
 *
 * Created on 26. April 2005, 13:38
 */

package gui;

/**
 *
 * @author  Standard
 */
public class frmAnzeige extends javax.swing.JFrame {
    public static int WIDTH=450;
    public static int HEIGHT=350;
    public static String TITLE="HICS - Treffen Sie Ihre Wahl!";
    
    /** Creates new form Anzeige */
    public frmAnzeige() {
        super(TITLE);
        initComponents();
        setSize(WIDTH, HEIGHT);
        show();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cmdNotiz = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cmdDaten = new javax.swing.JButton();
        cmdSonstiges = new javax.swing.JButton();
        cmdLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jPanel2.setBorder(new javax.swing.border.TitledBorder("Raumpflege"));
        cmdNotiz.setText("Notiz");
        cmdNotiz.setMaximumSize(new java.awt.Dimension(86, 23));
        cmdNotiz.setMinimumSize(new java.awt.Dimension(86, 23));
        cmdNotiz.setPreferredSize(new java.awt.Dimension(125, 30));
        cmdNotiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNotizActionPerformed(evt);
            }
        });

        jPanel2.add(cmdNotiz);

        jPanel1.add(jPanel2);

        jPanel3.setBorder(new javax.swing.border.TitledBorder("Hotelpersonal"));
        cmdDaten.setText("Daten erfassen");
        cmdDaten.setPreferredSize(new java.awt.Dimension(125, 30));
        cmdDaten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDatenActionPerformed(evt);
            }
        });

        jPanel3.add(cmdDaten);

        jPanel1.add(jPanel3);

        cmdSonstiges.setText("Sonstiges");
        cmdSonstiges.setMaximumSize(new java.awt.Dimension(110, 25));
        cmdSonstiges.setMinimumSize(new java.awt.Dimension(110, 25));
        cmdSonstiges.setPreferredSize(new java.awt.Dimension(125, 30));
        cmdSonstiges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSonstigesActionPerformed(evt);
            }
        });

        jPanel1.add(cmdSonstiges);

        cmdLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/logout.gif")));
        cmdLogout.setText("Ausloggen");
        cmdLogout.setMaximumSize(new java.awt.Dimension(95, 25));
        cmdLogout.setMinimumSize(new java.awt.Dimension(95, 25));
        cmdLogout.setPreferredSize(new java.awt.Dimension(125, 30));
        cmdLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLogoutActionPerformed(evt);
            }
        });

        jPanel1.add(cmdLogout);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void cmdSonstigesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSonstigesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdSonstigesActionPerformed

    private void cmdLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLogoutActionPerformed
        // TODO add your handling code here:
        this.hide();
        new frmStart().setVisible(true);
    }//GEN-LAST:event_cmdLogoutActionPerformed

    private void cmdDatenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDatenActionPerformed
        // TODO add your handling code here:
        this.hide();
        new frmDaten().setVisible(true);
    }//GEN-LAST:event_cmdDatenActionPerformed

    private void cmdNotizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNotizActionPerformed
        // TODO add your handling code here:
        this.hide();
        new frmInfo().setVisible(true);
    }//GEN-LAST:event_cmdNotizActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAnzeige().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdDaten;
    private javax.swing.JButton cmdLogout;
    private javax.swing.JButton cmdNotiz;
    private javax.swing.JButton cmdSonstiges;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
    
}
