/*
 * Anzeige.java
 *
 * Created on 26. April 2005, 13:38
 */

package gui;

/**
 *
 * @author  Standard
 */
public class frmDaten extends javax.swing.JFrame {
    public static int WIDTH=450;
    public static int HEIGHT=350;
    public static String TITLE="HICS - Daten";
    
    /** Creates new form Anzeige */
    public frmDaten() {
        super(TITLE);
        initComponents();
        setSize(WIDTH, HEIGHT);
        show();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cmdSuchen = new javax.swing.JButton();
        cmdSpeichern = new javax.swing.JButton();
        cmbDaten = new javax.swing.JComboBox();
        cmdBearbeiten = new javax.swing.JButton();
        cmdLoeschen = new javax.swing.JButton();
        cmdLoeschen1 = new javax.swing.JButton();
        lblAufgabe2 = new javax.swing.JLabel();
        lblAufgabe3 = new javax.swing.JLabel();
        lblAufgabe4 = new javax.swing.JLabel();
        tblInfo = new javax.swing.JTable();
        cmdNeu = new javax.swing.JButton();
        cmdZurueck = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cmdLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.EtchedBorder());
        cmdSuchen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/suchen.gif")));
        cmdSuchen.setText("Suchen");
        cmdSuchen.setMaximumSize(new java.awt.Dimension(95, 25));
        cmdSuchen.setMinimumSize(new java.awt.Dimension(95, 25));
        cmdSuchen.setOpaque(false);
        cmdSuchen.setPreferredSize(new java.awt.Dimension(125, 30));
        jPanel1.add(cmdSuchen, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        cmdSpeichern.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/speichern.gif")));
        cmdSpeichern.setText("Speichern");
        cmdSpeichern.setToolTipText("Klicken Sie hier um die ge\u00e4nderten Daten zu speichern!");
        cmdSpeichern.setMaximumSize(new java.awt.Dimension(95, 25));
        cmdSpeichern.setMinimumSize(new java.awt.Dimension(95, 25));
        cmdSpeichern.setOpaque(false);
        cmdSpeichern.setPreferredSize(new java.awt.Dimension(125, 30));
        jPanel1.add(cmdSpeichern, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 50, -1, -1));

        cmbDaten.addItem("Mitarbeiter");
        cmbDaten.addItem("Kunde");
        cmbDaten.addItem("Reservierung");
        cmbDaten.setEditable(false);
        cmbDaten.setMaximumSize(new java.awt.Dimension(110, 25));
        cmbDaten.setMinimumSize(new java.awt.Dimension(110, 25));
        cmbDaten.setOpaque(false);
        cmbDaten.setPreferredSize(new java.awt.Dimension(125, 30));
        cmbDaten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDatenActionPerformed(evt);
            }
        });

        jPanel1.add(cmbDaten, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        cmdBearbeiten.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/bearbeiten.gif")));
        cmdBearbeiten.setText("Bearbeiten");
        cmdBearbeiten.setToolTipText("Klicken Sie hier um Daten zu bearbeiten!\nKlicken Sie anschlie\u00dfend auf  \"Speichern\" um die \u00c4nderungen zu speichern!\nKlicken Sie anschlie\u00dfend auf  \"Abbrechen\" um die \u00c4nderungen nicht zu speichern!");
        cmdBearbeiten.setOpaque(false);
        cmdBearbeiten.setPreferredSize(new java.awt.Dimension(125, 30));
        jPanel1.add(cmdBearbeiten, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 10, -1, -1));

        cmdLoeschen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/loeschen.gif")));
        cmdLoeschen.setText("Loeschen");
        cmdLoeschen.setToolTipText("Klicken Sie  auf  \"L\u00f6schen\" um Daten zu l\u00f6schen!");
        cmdLoeschen.setMaximumSize(new java.awt.Dimension(95, 25));
        cmdLoeschen.setMinimumSize(new java.awt.Dimension(95, 25));
        cmdLoeschen.setOpaque(false);
        cmdLoeschen.setPreferredSize(new java.awt.Dimension(125, 30));
        jPanel1.add(cmdLoeschen, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 90, -1, -1));

        cmdLoeschen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/abbrechen.gif")));
        cmdLoeschen1.setText("Abbrechen");
        cmdLoeschen1.setToolTipText("Klicken Sie  auf  \"Abbrechen\" um die \u00c4nderungen nicht zu speichern!");
        cmdLoeschen1.setMaximumSize(new java.awt.Dimension(95, 25));
        cmdLoeschen1.setMinimumSize(new java.awt.Dimension(95, 25));
        cmdLoeschen1.setOpaque(false);
        cmdLoeschen1.setPreferredSize(new java.awt.Dimension(125, 30));
        cmdLoeschen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLoeschen1ActionPerformed(evt);
            }
        });

        jPanel1.add(cmdLoeschen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 130, -1, -1));

        lblAufgabe2.setFont(new java.awt.Font("Dialog", 1, 12));
        lblAufgabe2.setText("Thema");
        lblAufgabe2.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblAufgabe2.setMaximumSize(new java.awt.Dimension(95, 25));
        lblAufgabe2.setMinimumSize(new java.awt.Dimension(95, 25));
        lblAufgabe2.setPreferredSize(new java.awt.Dimension(95, 25));
        lblAufgabe2.setRequestFocusEnabled(false);
        jPanel1.add(lblAufgabe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 87, -1));

        lblAufgabe3.setFont(new java.awt.Font("Dialog", 1, 12));
        lblAufgabe3.setText("Aufgabe");
        lblAufgabe3.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblAufgabe3.setMaximumSize(new java.awt.Dimension(95, 25));
        lblAufgabe3.setMinimumSize(new java.awt.Dimension(95, 25));
        lblAufgabe3.setPreferredSize(new java.awt.Dimension(95, 25));
        lblAufgabe3.setRequestFocusEnabled(false);
        jPanel1.add(lblAufgabe3, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 50, 86, -1));

        lblAufgabe4.setFont(new java.awt.Font("Dialog", 1, 12));
        lblAufgabe4.setText("Details");
        lblAufgabe4.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblAufgabe4.setMaximumSize(new java.awt.Dimension(95, 25));
        lblAufgabe4.setMinimumSize(new java.awt.Dimension(95, 25));
        lblAufgabe4.setPreferredSize(new java.awt.Dimension(95, 25));
        lblAufgabe4.setRequestFocusEnabled(false);
        jPanel1.add(lblAufgabe4, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 50, 85, -1));

        tblInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Thema", "Aufgabe", "Details"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblInfo.setSurrendersFocusOnKeystroke(true);
        tblInfo.setTableHeader(null);
        jPanel1.add(tblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, 260, 170));

        cmdNeu.setText("Neu");
        cmdNeu.setToolTipText("Klicken Sie  auf  \"Neu\" um neue Daten anzulegen!");
        cmdNeu.setPreferredSize(new java.awt.Dimension(125, 30));
        jPanel1.add(cmdNeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 170, -1, -1));

        cmdZurueck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/zurueck.gif")));
        cmdZurueck.setText("Zurueck");
        cmdZurueck.setToolTipText("Klicken Sie  auf  \"Zurueck\" um wieder auf den vorigen Bildschirm zu gelangen!");
        cmdZurueck.setMaximumSize(new java.awt.Dimension(95, 25));
        cmdZurueck.setMinimumSize(new java.awt.Dimension(95, 25));
        cmdZurueck.setPreferredSize(new java.awt.Dimension(125, 30));
        cmdZurueck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdZurueckActionPerformed(evt);
            }
        });

        jPanel1.add(cmdZurueck, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 210, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(new javax.swing.border.EtchedBorder());
        cmdLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/logout.gif")));
        cmdLogout.setText("Ausloggen");
        cmdLogout.setToolTipText("Klicken Sie  auf  \"Ausloggen\" um wieder auf den Startbildschim zu gelangen!");
        cmdLogout.setMaximumSize(new java.awt.Dimension(95, 25));
        cmdLogout.setMinimumSize(new java.awt.Dimension(95, 25));
        cmdLogout.setPreferredSize(new java.awt.Dimension(125, 30));
        cmdLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLogoutActionPerformed(evt);
            }
        });

        jPanel2.add(cmdLogout);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void cmdZurueckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdZurueckActionPerformed
        // TODO add your handling code here:
        this.hide();
        new frmDaten().setVisible(true);
    }//GEN-LAST:event_cmdZurueckActionPerformed

    private void cmdLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLogoutActionPerformed
        // TODO add your handling code here:
        this.hide();
        new frmStart().setVisible(true);
    }//GEN-LAST:event_cmdLogoutActionPerformed

    private void cmdLoeschen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLoeschen1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_cmdLoeschen1ActionPerformed

    private void cmbDatenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDatenActionPerformed
        // TODO add your handling code here:
        int index = 0;
        /*
        boolean items = true;
        if(items != false) {
            cmbDaten.addItem("Mitarbeiter");
            cmbDaten.addItem("Kunde");
            cmbDaten.addItem("Reservierung");
            cmbDaten.addItem("Notiz");
            cmbDaten.setEditable(false);
            //cmbDaten.addActionListener(ComboAddHandler);
            items = false;
        }
         */
        
        index = cmbDaten.getSelectedIndex();
        if(index == 0) {
            new frmMitarbeiter().setVisible(true);
            this.hide();
        }
        if(index == 1) {
            new frmKundendaten().setVisible(true);
            this.hide();
        }
        if(index == 2) {
            new frmReservierung().setVisible(true);
            this.hide();
        }
                
        index = 4;
    }//GEN-LAST:event_cmbDatenActionPerformed

   /* public class ComboAddHandler implements ActionListener {
        
    }*/
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAnzeige().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbDaten;
    private javax.swing.JButton cmdBearbeiten;
    private javax.swing.JButton cmdLoeschen;
    private javax.swing.JButton cmdLoeschen1;
    private javax.swing.JButton cmdLogout;
    private javax.swing.JButton cmdNeu;
    private javax.swing.JButton cmdSpeichern;
    private javax.swing.JButton cmdSuchen;
    private javax.swing.JButton cmdZurueck;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAufgabe2;
    private javax.swing.JLabel lblAufgabe3;
    private javax.swing.JLabel lblAufgabe4;
    private javax.swing.JTable tblInfo;
    // End of variables declaration//GEN-END:variables
    
}
