/*
 * Anzeige.java
 *
 * Created on 26. April 2005, 13:38
 */

package gui;

/**
 *
 * @author  Standard
 */
public class frmNotiz extends javax.swing.JFrame {
    public static int WIDTH=450;
    public static int HEIGHT=350;
    public static String TITLE="HICS - Notiz";
    
    /** Creates new form Anzeige */
    public frmNotiz() {
        super(TITLE);
        initComponents();
        setSize(WIDTH, HEIGHT);
        show();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cmdSuchen = new javax.swing.JButton();
        cmdSpeichern = new javax.swing.JButton();
        cmbErledigen = new javax.swing.JComboBox();
        cmdBearbeiten = new javax.swing.JButton();
        cmdLoeschen = new javax.swing.JButton();
        cmdAbbrechen = new javax.swing.JButton();
        cmdNeu = new javax.swing.JButton();
        lblErledigen = new javax.swing.JLabel();
        txtErledigen = new javax.swing.JTextArea();
        cmbDringlichkeit = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        cmdLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.EtchedBorder());
        cmdSuchen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/suchen.gif")));
        cmdSuchen.setText("Suchen");
        cmdSuchen.setMaximumSize(new java.awt.Dimension(95, 25));
        cmdSuchen.setMinimumSize(new java.awt.Dimension(95, 25));
        cmdSuchen.setPreferredSize(new java.awt.Dimension(125, 30));
        jPanel1.add(cmdSuchen, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        cmdSpeichern.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/speichern.gif")));
        cmdSpeichern.setText("Speichern");
        cmdSpeichern.setMaximumSize(new java.awt.Dimension(95, 25));
        cmdSpeichern.setMinimumSize(new java.awt.Dimension(95, 25));
        cmdSpeichern.setPreferredSize(new java.awt.Dimension(125, 30));
        jPanel1.add(cmdSpeichern, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 50, -1, -1));

        cmbErledigen.addItem("Aufgabe");
        cmbErledigen.addItem("Notiz");
        cmbErledigen.setEditable(false);
        cmbErledigen.setMaximumSize(new java.awt.Dimension(110, 25));
        cmbErledigen.setMinimumSize(new java.awt.Dimension(110, 25));
        cmbErledigen.setPreferredSize(new java.awt.Dimension(125, 30));
        cmbErledigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbErledigenActionPerformed(evt);
            }
        });

        jPanel1.add(cmbErledigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        cmdBearbeiten.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/bearbeiten.gif")));
        cmdBearbeiten.setText("Bearbeiten");
        cmdBearbeiten.setPreferredSize(new java.awt.Dimension(125, 30));
        jPanel1.add(cmdBearbeiten, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 10, -1, -1));

        cmdLoeschen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/loeschen.gif")));
        cmdLoeschen.setText("Loeschen");
        cmdLoeschen.setMaximumSize(new java.awt.Dimension(95, 25));
        cmdLoeschen.setMinimumSize(new java.awt.Dimension(95, 25));
        cmdLoeschen.setPreferredSize(new java.awt.Dimension(125, 30));
        jPanel1.add(cmdLoeschen, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 90, -1, -1));

        cmdAbbrechen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/abbrechen.gif")));
        cmdAbbrechen.setText("Abbrechen");
        cmdAbbrechen.setMaximumSize(new java.awt.Dimension(95, 25));
        cmdAbbrechen.setMinimumSize(new java.awt.Dimension(95, 25));
        cmdAbbrechen.setPreferredSize(new java.awt.Dimension(125, 30));
        cmdAbbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAbbrechenActionPerformed(evt);
            }
        });

        jPanel1.add(cmdAbbrechen, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 130, -1, -1));

        cmdNeu.setText("Neu");
        cmdNeu.setPreferredSize(new java.awt.Dimension(125, 30));
        jPanel1.add(cmdNeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 170, -1, -1));

        lblErledigen.setText("Erledigen");
        lblErledigen.setMaximumSize(new java.awt.Dimension(95, 25));
        lblErledigen.setMinimumSize(new java.awt.Dimension(95, 25));
        lblErledigen.setPreferredSize(new java.awt.Dimension(95, 25));
        lblErledigen.setRequestFocusEnabled(false);
        jPanel1.add(lblErledigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtErledigen.setText("Hier stehen die anfallenden Taetigkeiten!");
        txtErledigen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        txtErledigen.setMinimumSize(new java.awt.Dimension(595, 34));
        txtErledigen.setPreferredSize(new java.awt.Dimension(383, 194));
        jPanel1.add(txtErledigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 170, 200));

        cmbDringlichkeit.setMaximumSize(new java.awt.Dimension(110, 25));
        cmbDringlichkeit.setMinimumSize(new java.awt.Dimension(110, 25));
        cmbDringlichkeit.setPreferredSize(new java.awt.Dimension(125, 30));
        cmbDringlichkeit.addItem("1");
        cmbDringlichkeit.addItem("2");
        cmbDringlichkeit.addItem("3");
        cmbDringlichkeit.addItem("4");
        cmbDringlichkeit.addItem("5");
        cmbDringlichkeit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDringlichkeitActionPerformed(evt);
            }
        });

        jPanel1.add(cmbDringlichkeit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(new javax.swing.border.EtchedBorder());
        cmdLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/logout.gif")));
        cmdLogout.setText("Ausloggen");
        cmdLogout.setMaximumSize(new java.awt.Dimension(95, 25));
        cmdLogout.setMinimumSize(new java.awt.Dimension(95, 25));
        cmdLogout.setPreferredSize(new java.awt.Dimension(125, 30));
        cmdLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLogoutActionPerformed(evt);
            }
        });

        jPanel2.add(cmdLogout);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void cmbDringlichkeitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDringlichkeitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDringlichkeitActionPerformed

    private void cmdLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLogoutActionPerformed
        // TODO add your handling code here:
        this.hide();
        new frmStart().setVisible(true);
    }//GEN-LAST:event_cmdLogoutActionPerformed

    private void cmdAbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAbbrechenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdAbbrechenActionPerformed

    private void cmbErledigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbErledigenActionPerformed
        // TODO add your handling code here:
        int index = 0;
        index = cmbErledigen.getSelectedIndex();
        if(index == 1) {
            lblErledigen.setText("Aufgabe");
            cmbDringlichkeit.setEditable(true);
        }
        if(index == 2) {
            lblErledigen.setText("Notiz");
            cmbDringlichkeit.setEditable(false);
        }     
        
    }//GEN-LAST:event_cmbErledigenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAnzeige().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbDringlichkeit;
    private javax.swing.JComboBox cmbErledigen;
    private javax.swing.JButton cmdAbbrechen;
    private javax.swing.JButton cmdBearbeiten;
    private javax.swing.JButton cmdLoeschen;
    private javax.swing.JButton cmdLogout;
    private javax.swing.JButton cmdNeu;
    private javax.swing.JButton cmdSpeichern;
    private javax.swing.JButton cmdSuchen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblErledigen;
    private javax.swing.JTextArea txtErledigen;
    // End of variables declaration//GEN-END:variables
    
}
