/*
 * Anzeige.java
 *
 * Created on 26. April 2005, 13:38
 */

package gui;



/**
 *
 * @author  Standard
 */
public class frmNotiz extends javax.swing.JFrame {
    public static int WIDTH=500;
    public static int HEIGHT=350;
    public static String TITLE="HICS - Notiz";
    
    /** Creates new form Anzeige */
    public frmNotiz() {
        super(TITLE);
        initComponents();
        setSize(WIDTH, HEIGHT);
        show();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        cmdSuchen = new javax.swing.JButton();
        cmdSpeichern = new javax.swing.JButton();
        cmbErledigen = new javax.swing.JComboBox();
        cmdBearbeiten = new javax.swing.JButton();
        cmdLoeschen = new javax.swing.JButton();
        cmdAbbrechen = new javax.swing.JButton();
        cmdNeu = new javax.swing.JButton();
        lblErledigen = new javax.swing.JLabel();
        txtErledigen = new javax.swing.JTextArea();
        cmbDringlichkeit = new javax.swing.JComboBox();
        cmdZurueck = new javax.swing.JButton();
        pnlLogout = new javax.swing.JPanel();
        cmdLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(500, 350));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 350));
        cmdSuchen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/suchen.gif")));
        cmdSuchen.setMaximumSize(new java.awt.Dimension(95, 25));
        cmdSuchen.setMinimumSize(new java.awt.Dimension(10, 30));
        cmdSuchen.setPreferredSize(new java.awt.Dimension(10, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(cmdSuchen, gridBagConstraints);

        cmdSpeichern.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/speichern.gif")));
        cmdSpeichern.setMaximumSize(new java.awt.Dimension(95, 25));
        cmdSpeichern.setMinimumSize(new java.awt.Dimension(10, 30));
        cmdSpeichern.setPreferredSize(new java.awt.Dimension(10, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(cmdSpeichern, gridBagConstraints);

        cmbErledigen.addItem("Aufgabe");
        cmbErledigen.addItem("Notiz");
        cmbErledigen.setEditable(false);
        cmbErledigen.setMaximumSize(new java.awt.Dimension(110, 25));
        cmbErledigen.setMinimumSize(new java.awt.Dimension(110, 25));
        cmbErledigen.setPreferredSize(new java.awt.Dimension(125, 30));
        cmbErledigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbErledigenActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(cmbErledigen, gridBagConstraints);

        cmdBearbeiten.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/bearbeiten.gif")));
        cmdBearbeiten.setMinimumSize(new java.awt.Dimension(10, 30));
        cmdBearbeiten.setPreferredSize(new java.awt.Dimension(10, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(cmdBearbeiten, gridBagConstraints);

        cmdLoeschen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/loeschen.gif")));
        cmdLoeschen.setMaximumSize(new java.awt.Dimension(95, 25));
        cmdLoeschen.setMinimumSize(new java.awt.Dimension(30, 30));
        cmdLoeschen.setPreferredSize(new java.awt.Dimension(10, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(cmdLoeschen, gridBagConstraints);

        cmdAbbrechen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/abbrechen.gif")));
        cmdAbbrechen.setMaximumSize(new java.awt.Dimension(95, 25));
        cmdAbbrechen.setMinimumSize(new java.awt.Dimension(10, 30));
        cmdAbbrechen.setPreferredSize(new java.awt.Dimension(10, 30));
        cmdAbbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAbbrechenActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(cmdAbbrechen, gridBagConstraints);

        cmdNeu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/neu.gif")));
        cmdNeu.setMaximumSize(new java.awt.Dimension(10, 30));
        cmdNeu.setMinimumSize(new java.awt.Dimension(10, 30));
        cmdNeu.setOpaque(false);
        cmdNeu.setPreferredSize(new java.awt.Dimension(10, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(cmdNeu, gridBagConstraints);

        lblErledigen.setText("Erledigen");
        lblErledigen.setMaximumSize(new java.awt.Dimension(95, 25));
        lblErledigen.setMinimumSize(new java.awt.Dimension(95, 25));
        lblErledigen.setPreferredSize(new java.awt.Dimension(95, 25));
        lblErledigen.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(lblErledigen, gridBagConstraints);

        txtErledigen.setText("Hier stehen die anfallenden Taetigkeiten!");
        txtErledigen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        txtErledigen.setMinimumSize(new java.awt.Dimension(595, 34));
        txtErledigen.setPreferredSize(new java.awt.Dimension(300, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(txtErledigen, gridBagConstraints);

        cmbDringlichkeit.setMaximumSize(new java.awt.Dimension(110, 25));
        cmbDringlichkeit.setMinimumSize(new java.awt.Dimension(110, 25));
        cmbDringlichkeit.setPreferredSize(new java.awt.Dimension(125, 30));
        cmbDringlichkeit.addItem("1");
        cmbDringlichkeit.addItem("2");
        cmbDringlichkeit.addItem("3");
        cmbDringlichkeit.addItem("4");
        cmbDringlichkeit.addItem("5");
        cmbDringlichkeit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDringlichkeitActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = -45;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(cmbDringlichkeit, gridBagConstraints);

        cmdZurueck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/zurueck.gif")));
        cmdZurueck.setToolTipText("Klicken Sie  auf  \"Zurueck\" um wieder auf den vorigen Bildschirm zu gelangen!");
        cmdZurueck.setMaximumSize(new java.awt.Dimension(53, 23));
        cmdZurueck.setMinimumSize(new java.awt.Dimension(25, 25));
        cmdZurueck.setPreferredSize(new java.awt.Dimension(10, 30));
        cmdZurueck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdZurueckActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(cmdZurueck, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pnlLogout.setMinimumSize(new java.awt.Dimension(500, 44));
        pnlLogout.setPreferredSize(new java.awt.Dimension(500, 44));
        cmdLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/logout.gif")));
        cmdLogout.setText("Ausloggen");
        cmdLogout.setMaximumSize(new java.awt.Dimension(95, 25));
        cmdLogout.setMinimumSize(new java.awt.Dimension(95, 25));
        cmdLogout.setPreferredSize(new java.awt.Dimension(125, 30));
        cmdLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLogoutActionPerformed(evt);
            }
        });

        pnlLogout.add(cmdLogout);

        getContentPane().add(pnlLogout, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void cmdZurueckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdZurueckActionPerformed
        // TODO add your handling code here:
        this.hide();
        new frmDaten().setVisible(true);   
    }//GEN-LAST:event_cmdZurueckActionPerformed

    private void cmbDringlichkeitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDringlichkeitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDringlichkeitActionPerformed

    private void cmdLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLogoutActionPerformed
        // TODO add your handling code here:
        this.hide();
        new frmStart().setVisible(true);
    }//GEN-LAST:event_cmdLogoutActionPerformed

    private void cmdAbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAbbrechenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdAbbrechenActionPerformed

    private void cmbErledigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbErledigenActionPerformed
        // TODO add your handling code here:
        int index = 0;
        index = cmbErledigen.getSelectedIndex();
        if(index == 1) {
            lblErledigen.setText("Aufgabe");
            cmbDringlichkeit.setEditable(true);
        }
        if(index == 2) {
            lblErledigen.setText("Notiz");
            cmbDringlichkeit.setEditable(false);
        }     
        
    }//GEN-LAST:event_cmbErledigenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNotiz().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbDringlichkeit;
    private javax.swing.JComboBox cmbErledigen;
    private javax.swing.JButton cmdAbbrechen;
    private javax.swing.JButton cmdBearbeiten;
    private javax.swing.JButton cmdLoeschen;
    private javax.swing.JButton cmdLogout;
    private javax.swing.JButton cmdNeu;
    private javax.swing.JButton cmdSpeichern;
    private javax.swing.JButton cmdSuchen;
    private javax.swing.JButton cmdZurueck;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblErledigen;
    private javax.swing.JPanel pnlLogout;
    private javax.swing.JTextArea txtErledigen;
    // End of variables declaration//GEN-END:variables
    
}
