/*
 * frmZimmer.java
 *
 * Created on 29. Mai 2005, 20:09
 */

package gui;

/**
 *
 * @author  Sabrina
 */
public class frmZimmer extends javax.swing.JFrame {
     public static int WIDTH=350;
    public static int HEIGHT=300;
    public static String TITLE="HICS - Zimmer Details";
    
    /** Creates new form frmInfo */
    public frmZimmer() {
        super(TITLE);
        initComponents();
        setSize(WIDTH, HEIGHT);
    }
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        txtZimNr = new javax.swing.JTextField();
        txtBettenAnz = new javax.swing.JTextField();
        txtPreis = new javax.swing.JTextField();
        lblZimNr = new javax.swing.JLabel();
        lblBettenAnz = new javax.swing.JLabel();
        lblPreis = new javax.swing.JLabel();
        lblAusstattung = new javax.swing.JLabel();
        txtAreaAusstattung = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        txtZimNr.setBackground(new java.awt.Color(236, 233, 216));
        txtZimNr.setText("101");
        txtZimNr.setBorder(null);
        txtZimNr.setPreferredSize(new java.awt.Dimension(62, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(txtZimNr, gridBagConstraints);

        txtBettenAnz.setBackground(new java.awt.Color(236, 233, 216));
        txtBettenAnz.setText("XX X");
        txtBettenAnz.setBorder(null);
        txtBettenAnz.setPreferredSize(new java.awt.Dimension(62, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(txtBettenAnz, gridBagConstraints);

        txtPreis.setBackground(new java.awt.Color(236, 233, 216));
        txtPreis.setText("200 \u20ac ");
        txtPreis.setBorder(null);
        txtPreis.setPreferredSize(new java.awt.Dimension(62, 20));
        txtPreis.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(txtPreis, gridBagConstraints);

        lblZimNr.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        lblZimNr.setText("Zimmer");
        lblZimNr.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(lblZimNr, gridBagConstraints);

        lblBettenAnz.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        lblBettenAnz.setText("Betten");
        lblBettenAnz.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(lblBettenAnz, gridBagConstraints);

        lblPreis.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        lblPreis.setText("Preis / Nacht");
        lblPreis.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(lblPreis, gridBagConstraints);

        lblAusstattung.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        lblAusstattung.setText("Ausstattung");
        lblAusstattung.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(lblAusstattung, gridBagConstraints);

        txtAreaAusstattung.setBackground(new java.awt.Color(236, 233, 216));
        txtAreaAusstattung.setFont(new java.awt.Font("Arial", 0, 12));
        txtAreaAusstattung.setRows(4);
        txtAreaAusstattung.setText("Fernseher,\nVideo");
        txtAreaAusstattung.setDisabledTextColor(new java.awt.Color(236, 233, 216));
        txtAreaAusstattung.setPreferredSize(new java.awt.Dimension(100, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(txtAreaAusstattung, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmZimmer().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAusstattung;
    private javax.swing.JLabel lblBettenAnz;
    private javax.swing.JLabel lblPreis;
    private javax.swing.JLabel lblZimNr;
    private javax.swing.JTextArea txtAreaAusstattung;
    private javax.swing.JTextField txtBettenAnz;
    private javax.swing.JTextField txtPreis;
    private javax.swing.JTextField txtZimNr;
    // End of variables declaration//GEN-END:variables
    
}
